"""Initiative Canvas — A3 one-pager export for any initiative."""

from __future__ import annotations
from textwrap import dedent


def render_canvas(ini: dict, outcomes: list, suites: list, eval_runs: dict,
                  entries: list, gate: dict, dr: dict, score: dict,
                  roi: dict, value_summary: dict) -> str:
    """Render an initiative as a markdown A3 canvas."""

    sev = ini.get("severity_class", "—")
    loop = ini.get("current_loop", "—")
    phase = ini.get("current_phase", "—")
    autonomy = ini.get("autonomy_level", "L0")
    ttype = ini.get("transformation_type", "—")

    # Outcomes section
    outcome_rows = ""
    for o in outcomes:
        outcome_rows += f"| {o.get('metric','—')} | {o.get('baseline','—')} | {o.get('target_range','—')} | {o.get('timeframe','—')} |\n"
    if not outcome_rows:
        outcome_rows = "| _No outcomes defined_ | | | |\n"

    # Eval status
    eval_rows = ""
    for s in suites:
        run = eval_runs.get(s["level"])
        if run:
            rate = f"{run['pass_rate']:.1%} ({run['passed']}/{run['total']})"
        else:
            rate = "No runs"
        eval_rows += f"| {s['level']} | {s.get('description','')[:60]} | {rate} |\n"
    if not eval_rows:
        eval_rows = "| _No eval suites_ | | |\n"

    # PDCA summary (last 5 entries)
    pdca_lines = ""
    for e in entries[-5:]:
        pdca_lines += f"- **{e['phase'].upper()}**: {e['note'][:80]}\n"
    if not pdca_lines:
        pdca_lines = "_No PDCA entries_\n"

    # Gate status
    gate_status = "✅ PASS" if gate and gate.get("passed") else "🚫 BLOCKED"
    gate_reason = gate.get("reason", "") if gate else ""

    # Data readiness
    dr_score = "—"
    if dr:
        dr_score = f"{dr.get('total_score', '—')}/18"

    # PMO score
    pmo_total = "—"
    pmo_verdict = ""
    if score:
        pmo_total = f"{score.get('total', '—')}/40"
        t = score.get("total", 0)
        pmo_verdict = "FAST-TRACK" if t >= 24 else "CONDITIONAL" if t >= 16 else "NOT QUALIFIED"

    # ROI
    roi_line = "—"
    if roi:
        net = (roi.get("value_captured", 0) or 0) - (roi.get("tco_to_date", 0) or 0)
        roi_line = f"Created: ${roi.get('value_created', 0):,.0f} | Captured: ${roi.get('value_captured', 0):,.0f} | TCO: ${roi.get('tco_to_date', 0):,.0f} | **Net: ${net:,.0f}** ({roi.get('confidence', '—')})"

    # Value summary
    val_line = ""
    if value_summary:
        tc = value_summary.get("total_created", 0) or 0
        tcap = value_summary.get("total_captured", 0) or 0
        if tc or tcap:
            rate = (tcap / tc * 100) if tc else 0
            val_line = f"Value Created: ${tc:,.0f} | Value Captured: ${tcap:,.0f} | Capture Rate: {rate:.0f}%"

    return dedent(f"""\
# 📋 Initiative Canvas: {ini['name']}

| | |
|---|---|
| **Severity** | {sev} |
| **Transformation** | {ttype} |
| **Loop → Phase** | {loop} → {phase} |
| **Autonomy Level** | {autonomy} |
| **Status** | {ini.get('status', 'active')} |

> {ini.get('description', '_No description_')}

---

## 🎯 Outcomes

| Metric | Baseline | Target | Timeframe |
|--------|----------|--------|-----------|
{outcome_rows}
## 🧪 Eval Status

| Level | Description | Latest |
|-------|-------------|--------|
{eval_rows}
**Gate Check**: {gate_status} {gate_reason}

---

## 🔄 PDCA Log (latest)

{pdca_lines}
---

## 📊 Scores & Readiness

| Dimension | Score |
|-----------|-------|
| **PMO Score** | {pmo_total} {pmo_verdict} |
| **Data Readiness** | {dr_score} |

## 💰 ROI

{roi_line}

{val_line}

---

_Generated by AI-Kaizen • {ini.get('updated_at', '')[:10]}_
""")
